language: node_js
node_js:
  - v7
  - v6
  - v5
  - v4

install:
  - npm install -g codecov
script:
  - npm run unit
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
